function m(c,a,b,d){c.h.pa(c.fa,a,b,d)}function p(c,a,b,d){c.h.s?m(c,a,b,d):c.h.Qb()._OnMessageFromDOM({type:"event",component:c.fa,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function t(c,a,b){c.h.i(c.fa,a,b)}function u(c,a){for(const [b,d]of a)t(c,b,d)}window.G=class{constructor(c,a){this.h=c;this.fa=a}ya(){}};window.zc=class{constructor(){}};"use strict";class aa{constructor(c){this.ga=c;this.Na=!1;this.Qa=!0;this.ha=this.D=this.Za=-1}}
function ba(c,a){const b=a.elementId,d=c.R(b,a),e=new aa(d);c.O.set(b,e);d.style.boxSizing="border-box";d.style.display="none";e.Qa=!!a.isVisible;var f=c.Ea(d);f.addEventListener("focus",()=>{v(c,"elem-focused",b)});f.addEventListener("blur",()=>{v(c,"elem-blurred",b)});f=a.htmlIndex;e.Za=f;e.ha=a.htmlZIndex;c.U&&(a=c.h.Ba(f),e.D=a,c.h.ba(a).appendChild(d))}function w(c,a,b){t(c,a,d=>{const e=x(c,d.elementId);return b(e,d)})}
function x(c,a){c=c.O.get(a);if(!c)throw Error(`no element with id ${a}`);return c.ga}function v(c,a,b,d){d||(d={});d.elementId=b;m(c,a,d)}function y(c,a,b,d){d||(d={});d.elementId=b;p(c,a,d)}
window.L=class extends self.G{constructor(c,a){super(c,a);this.O=new Map;this.U=!0;u(this,[["create",b=>ba(this,b)],["destroy",b=>{b=b.elementId;const d=x(this,b);this.U&&d.parentElement.removeChild(d);this.O.delete(b)}],["set-visible",b=>{if(this.U){var d=this.O.get(b.elementId),e=d.ga;d.Na?e.style.display=b.isVisible?"":"none":d.Qa=!!b.isVisible}}],["update-position",b=>{if(this.U){var d=this.O.get(b.elementId),e=d.ga,f=this.h;e.style.left=b.left+"px";e.style.top=b.top+"px";e.style.width=b.width+
"px";e.style.height=b.height+"px";var h=b.fontSize;null!==h&&(e.style.fontSize=h+"em");h=b.htmlIndex;d.Za=h;h=f.Ba(h);h!==d.D&&(e.remove(),f.ba(h).appendChild(e),d.D=h,f.Ka());b=b.htmlZIndex;b!==d.ha&&(d.ha=b,f.Ka());d.Na||(d.Na=!0,d.Qa&&(e.style.display=""))}}],["update-state",b=>{const d=x(this,b.elementId);this.u(d,b)}],["focus",b=>this.Ha(b)],["set-css-style",b=>{const d=x(this,b.elementId),e=b.prop;b=b.val;e.startsWith("--")?d.style.setProperty(e,b):d.style[e]=b}],["set-attribute",b=>{x(this,
b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{x(this,b.elementId).removeAttribute(b.name)}]]);w(this,"get-element",b=>b)}R(){throw Error("required override");}u(){throw Error("required override");}Ea(c){return c}Ha(c){const a=this.Ea(x(this,c.elementId));c.focus?a.focus():a.blur()}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),z=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let ea=0;function A(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.pc?new Promise(b=>{const d="c3_resolve_"+ea;++ea;self[d]=b;a.textContent=c.tc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}
async function fa(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let c=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){c=!0}}),b=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return c&&b}catch(c){return console.warn("Error feature detecting worker mode: ",c),!1}}let B=new Audio;
const ha={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function ia(c){c=await ja(c);return(new TextDecoder("utf-8")).decode(c)}
function ja(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const C=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,H=new Map;let ka=0;const la=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");la.push(c)};const ma=new Set(["cordova","playable-ad","instant-games"]);let na=!1;
window.j=class c{constructor(a){this.s=a.vc;this.ka=null;this.o="";this.X=a.sc;this.na={};this.Sa=this.Z=null;this.V=[];this.P=null;this.wb=!0;this.l=[];this.Wa=[];this.Xa=!1;this.yb=()=>this.Ob();this.vb=!1;this.ia=null;this.W=-1;this.lc=()=>this.Zb();this.la=new Set;this.$a=null;this.zb=[];this.g=a.Ab;this.Pa="file"===location.protocol.substr(0,4);this.rb=[];if("playable-ad"===this.g||"instant-games"===this.g)this.s=!1;da&&(this.s=!1);if("cordova"===this.g&&this.s&&z){const b=/Chrome\/(\d+)/i.exec(navigator.userAgent);
b&&90<=parseInt(b[1],10)||(this.s=!1)}this.B()?self.chrome.webview.addEventListener("message",b=>this.mb(b.data,b.additionalObjects)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=b=>this.mb(b));this.ta=this.F=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.i("canvas","update-size",b=>this.cc(b));this.i("canvas",
"set-html-layer-count",b=>this._OnSetHTMLLayerCount(b));this.i("canvas","cleanup-html-layers",()=>this.Ub());this.i("runtime","cordova-fetch-local-file",b=>this.Vb(b));this.i("runtime","create-job-worker",()=>this.Wb());this.i("runtime","send-wrapper-extension-message",b=>this.bc(b));"cordova"===this.g?document.addEventListener("deviceready",()=>this.S(a)):this.S(a)}cb(){return this.l[0].canvas}Ba(a){return Math.min(a,this.l.length-1)}ba(a){if(0>a||a>=this.l.length)throw new RangeError("invalid canvas layer");
return this.l[a].oa}_GetHTMLWrapElement(a){return this.ba(a)}Fb(){return ca&&"cordova"===this.g}da(){const a=navigator.userAgent;return ca&&ma.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Db(){return z}eb(){return z&&ma.has(this.g)}fb(){return"windows-webview2"===this.g||!!("preview"===this.g&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}B(){return this.fb()||"xbox-uwp-webview2"===this.g}async S(a){this.s&&!await fa()&&(this.s=!1);"macos-wkwebview"===
this.g?this.M({type:"ready"}):this.B()&&(this.fc(),this.zb=(await this.Tb()).registeredComponentIds);if("playable-ad"===this.g){this.F=self.c3_base64files;this.ta={};await this.Lb();for(let d=0,e=a.$.length;d<e;++d){var b=a.$[d];this.ta.hasOwnProperty(b)?a.$[d]={pc:!0,tc:this.ta[b]}:this.F.hasOwnProperty(b)&&(a.$[d]=URL.createObjectURL(this.F[b]))}a.xa=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.gb(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":
"0.999"})}a.rc?this.o=a.rc:(b=location.origin,this.o=("null"===b?"file:///":b)+location.pathname,b=this.o.lastIndexOf("/"),-1!==b&&(this.o=this.o.substr(0,b+1)));a.xc&&(this.na=a.xc);b=new MessageChannel;this.ka=b.port1;this.ka.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Yb(d));this.ia=new self.Gb(this);await oa(this.ia);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,
e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.s?await this.Sb(a,b.port2):await this.Rb(a,b.port2)}Fa(a){a=this.na.hasOwnProperty(a)?this.na[a]:a.endsWith("/workermain.js")&&this.na.hasOwnProperty("workermain.js")?this.na["workermain.js"]:"playable-ad"===this.g&&this.F.hasOwnProperty(a)?this.F[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async Aa(a,b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===
this.g&&this.Pa)return a=await this.za(d.oc?a:this.X+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}C(){return Math.max(window.innerWidth,1)}v(){return Math.max(window.innerHeight,1)}Ca(){return this.B()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.g)?
"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}kb(a){var b=this.o,d=location.href,e=this.C(),f=this.v(),h=this.Ca(),g=window.devicePixelRatio,k=c.ca(),l=a.Dc,n=window.cr_previewImageBlobs||this.F,q=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,Ra=window.cr_swClientId||
"";a=a.Ab;var Sa=(new URLSearchParams(self.location.search)).has("debug"),Y=this.ia;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:h,devicePixelRatio:g,isFullscreen:k,projectData:l,previewImageBlobs:n,previewProjectFileBlobs:q,previewProjectFileSWUrls:r,swClientId:Ra,exportType:a,isDebug:Sa,ife:!!self.Cc,jobScheduler:{inputPort:Y.Oa,outputPort:Y.Va,maxNumWorkers:Y.jc},supportedAudioFormats:ha,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.X+"opus.wasm.js",
opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.X+"opus.wasm.wasm",isFileProtocol:this.Pa,isiOSCordova:this.Fb(),isiOSWebView:this.da(),isWindowsWebView2:this.fb(),isAnyWebView2Wrapper:this.B(),wrapperComponentIds:this.zb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Sb(a,b){const d=this.Fa(a.wc);"preview"===this.g?(this.Z=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,n)=>{const q=r=>{this.Z.removeEventListener("message",q);r.data&&"ok"===
r.data.type?l():n()};this.Z.addEventListener("message",q);this.Z.postMessage({type:"construct-worker-init","import":(new URL(d,this.o)).toString()})})):this.Z=await this.Aa(d,this.o,{type:"module",name:"Runtime",oc:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this.l.push({canvas:e,oa:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&
self.C3_InsertHTMLPlaceholders();let g=a.xa||[],k=a.$;g=await Promise.all(g.map(l=>this.T(l)));k=await Promise.all(k.map(l=>this.T(l)));if("cordova"===this.g)for(let l=0,n=a.wa.length;l<n;++l){const q=a.wa[l],r=q[0];if(r===a.ab||"scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))q[1]=await this.T(r)}this.Z.postMessage(Object.assign(this.kb(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:f,workerDependencyScripts:g,engineScripts:k,projectScripts:a.wa,mainProjectScript:a.ab,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[b,f,...pa(this.ia)]);this.V=E.map(l=>new l(this));this.jb();I(e);qa(h);ra(this.P);self.c3_callFunction=(l,n)=>{var q=this.P;return q.h.Hb(q.fa,{name:l,params:n})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.pa("runtime","go-to-last-error-script"))}async Rb(a,b){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.l.push({canvas:d,oa:e});window.c3canvas=
d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.V=E.map(g=>new g(this));this.jb();I(d);qa(e);e=a.$.map(g=>"string"===typeof g?(new URL(g,this.o)).toString():g);if(Array.isArray(a.xa)){var f=[...a.xa].map(g=>g instanceof Blob?URL.createObjectURL(g):g);e.unshift(...f)}e=await Promise.all(e.map(g=>this.T(g)));await Promise.all(e.map(g=>A(g)));e=self.C3_ProjectScriptsStatus;f=a.ab;const h=a.wa;for(let [g,k]of h)if(k||(k=g),g===f)try{k=await this.T(k),await A(k),"preview"!==this.g||
e[g]||this.nb(g,"main script did not run to completion")}catch(l){this.nb(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))k=await this.T(k),await A(k);"preview"===this.g&&"object"!==typeof self.yc.Ac?(this.ra(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.kb(a),{isInWorker:!1,
messagePort:b,canvas:d,runOnStartupFunctions:la}),ra(this.P),this.lb(),this.Sa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Sa,a))}nb(a,b){this.ra();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}lb(){this.ra()}ra(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=
null)}async Wb(){const a=await sa(this.ia);return{outputPort:a,transferables:[a]}}cc(a){if(!this.vb){var b=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,oa:g}of this.l)h.style.width=b,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,g.style.width=b,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,this.wb&&(h.style.display="",g.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.wb=
!1}}_OnSetHTMLLayerCount(a){var b=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const h=a.marginLeft+"px",g=a.marginTop+"px";a=[];const k=[];if(b<this.l.length)for(;this.l.length>b;){const {canvas:l,oa:n}=this.l.pop();n.remove();this.s&&!d?this.Wa.push(l):l.remove()}else if(b>this.l.length)for(let l=0,n=b-this.l.length;l<n;++l)b=document.createElement("canvas"),b.classList.add("c3overlay"),this.s?(d=b.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(b),document.body.appendChild(b),
d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),b.style.width=e,b.style.height=f,b.style.marginLeft=h,b.style.marginTop=g,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=g,I(b),qa(d),this.l.push({canvas:b,oa:d});for(const l of this.V)if(l instanceof window.L&&l.U)for(const n of l.O.values())e=l.h.Ba(n.Za),f=n.D,-1!==e&&-1!==f&&e!==f&&(f=n.ga,f.remove(),l.h.ba(e).appendChild(f),n.D=e);this.Ka();return{addedCanvases:a,transferables:k}}Ub(){for(const a of this.Wa)a.remove();
this.Wa.length=0}Ka(){this.Xa||(this.Xa=!0,this.gb(this.yb))}Ob(){this.ec(this.yb);this.Xa=!1;let a=[];for(var b of this.V)if(b instanceof window.L){var d=b.U?[...b.O.values()]:null;d&&a.push(...d)}a.sort((h,g)=>{const k=h.D,l=g.D;return k!==l?k-l:h.ha-g.ha});let e=d=b=0,f=a.length;for(;e<f;++e){const h=a[e];h.D!==b&&(this.ib(b,a.slice(d,e)),b=h.D,d=e)}d<e&&this.ib(b,a.slice(d,e))}ib(a,b){if(!(1>=b.length||a>=this.l.length)){b=b.map(k=>k.ga);var d=new Set(b);a=this.ba(a);for(var e=Array.from(a.children).filter(k=>
d.has(k)),f=0,h=Math.min(b.length,e.length);f<h&&b[f]===e[f];++f);for(var g=f;g<h;++g)e[g].remove();for(g=f;g<h;++g)a.appendChild(b[g])}}Qb(){if(this.s)throw Error("not available in worker mode");return this.Sa}pa(a,b,d,e){this.ka.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}Hb(a,b){const d=ka++,e=new Promise((f,h)=>{H.set(d,{resolve:f,reject:h})});this.ka.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,
responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=a.type;if("event"===b)return this.Xb(a);if("result"===b)this.$b(a);else if("runtime-ready"===b)this.ac();else if("alert-error"===b)this.ra(),alert(a.message);else if("creating-runtime"===b)this.lb();else throw Error(`unknown message '${b}'`);}Xb(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(b))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${b}' handler '${d}':`,g);null!==f&&this.qa(f,
!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.qa(f,!0,g)).catch(g=>{console.error(`Rejection from '${b}' handler '${d}':`,g);this.qa(f,!1,""+g)}):this.qa(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}qa(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.ka.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}$b(a){const b=a.responseId,d=a.isOk;a=a.result;const e=H.get(b);d?e.resolve(a):
e.reject(a);H.delete(b)}i(a,b,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);e.set(b,d)}static m(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}jb(){for(const a of this.V)if("runtime"===a.fa){this.P=a;return}throw Error("cannot find runtime DOM handler");}Yb(a){this.pa("debugger","message",a)}ac(){for(const a of this.V)a.ya()}static ca(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||na)}static sa(a){na=!!a}gb(a){this.la.add(a);this.Ja()}ec(a){this.la.delete(a);0===this.la.size&&this.hb()}Ja(){-1===this.W&&0<this.la.size&&(this.W=requestAnimationFrame(this.lc))}hb(){-1!==this.W&&(cancelAnimationFrame(this.W),this.W=-1)}Zb(){this.W=-1;for(const a of this.la)a();this.Ja()}Ia(){this.P.Ia()}Ib(){this.vb=!0}Cb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Eb(a){return!this.Cb(a)}async T(a){return"cordova"===
this.g&&(a.startsWith("file:")||this.Pa&&this.Eb(a))?(a.startsWith(this.o)&&(a=a.substr(this.o.length)),a=await this.za(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Vb(a){const b=a.filename;switch(a.as){case "text":return await this.Bb(b);case "buffer":return await this.za(b);default:throw Error("unsupported type");}}bb(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async Bb(a){a=
await this.bb(a);return await ia(a)}Da(){if(C.length&&!(8<=D)){D++;var a=C.shift();this.Mb(a.filename,a.uc,a.nc)}}za(a){return new Promise((b,d)=>{C.push({filename:a,uc:e=>{D--;this.Da();b(e)},nc:e=>{D--;this.Da();d(e)}});this.Da()})}async Mb(a,b,d){try{const e=await this.bb(a),f=await ja(e);b(f)}catch(e){d(e)}}mb(a,b){if("entered-fullscreen"===a)c.sa(!0),J(this.P);else if("exited-fullscreen"===a)c.sa(!1),J(this.P);else if("object"===typeof a){const d=a.type;"directory-handles"===d?this.rb=b:"wrapper-init-response"===
d?(this.$a(a),this.$a=null):"extension-message"===d?this.pa("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}bc(a){this.M({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}M(a){this.B()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}fc(){window.moveTo=
(a,b)=>{this.M({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(b)})};window.resizeTo=(a,b)=>{this.M({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}Tb(){return this.B()?new Promise(a=>{this.$a=a;this.M({type:"wrapper-init"})}):Promise.resolve()}async Lb(){const a=[];for(const [b,d]of Object.entries(this.F))a.push(this.Kb(b,d));await Promise.all(a)}async Kb(a,b){if("object"===typeof b)this.F[a]=new Blob([b.str],{type:b.type}),this.ta[a]=b.str;else{let d=
await this.Pb(b);d||(d=this.Nb(b));this.F[a]=d}}async Pb(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",b),null}}Nb(a){a=this.dc(a);return this.Jb(a.data,a.qc)}dc(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");
a=b[0]||"";const e=b[2];d="base64"===b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{qc:a,data:d}}Jb(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";
const K=self.j,ta=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),M={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ua={dispatchUserScriptEvent:!0},va={dispatchRuntimeEvent:!0};function wa(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}function xa(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}
async function ya(c){c=URL.createObjectURL(c);try{return await xa(c)}finally{URL.revokeObjectURL(c)}}function za(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const Aa=new Set(["input","textarea","datalist","select"]),Ba=new Set(["canvas","body","html"]);function N(c){c.target.tagName&&Ba.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function Ca(c){c.target.tagName&&c.target.classList.contains("c3htmlwrap")&&c.preventDefault()}
function Da(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}self.C3_GetSvgImageSize=async function(c){c=await ya(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};
self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await ya(c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};let Ea=!1;document.addEventListener("pause",()=>Ea=!0);document.addEventListener("resume",()=>Ea=!1);function I(c){c.addEventListener("selectstart",N);c.addEventListener("gesturehold",N);c.addEventListener("pointerdown",N)}
function qa(c){c.addEventListener("selectstart",Ca);c.addEventListener("gesturehold",Ca);c.addEventListener("touchstart",Ca)}function ra(c){c.tb=!0;c.Ra=c.h.C();c.ja=c.h.v()}function J(c){if(!c.A){var a=K.ca();a&&"any"!==c.Ya&&Fa(c);m(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.C(),innerHeight:c.v()})}}async function Ga(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ha(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Ia(c){return await self.C3_GetSvgImageSize(c.blob)}function Ja(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function Ka(c){self.setTimeout(()=>{c.sb=!0},1E3);"cordova"===c.h.g?(document.addEventListener("pause",()=>La(c,!0)),document.addEventListener("resume",()=>La(c,!1))):document.addEventListener("visibilitychange",()=>La(c,"hidden"===document.visibilityState));c.ua=!("hidden"!==document.visibilityState&&!Ea);return{isSuspended:c.ua}}
function Ma(c){c.pb||(c.pb=!0,window.addEventListener("deviceorientation",a=>{c.A||m(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},M)}),window.addEventListener("deviceorientationabsolute",a=>{c.A||m(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},M)}))}
function Na(c){c.ob||(c.ob=!0,window.addEventListener("devicemotion",a=>{if(!c.A){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},M)}}))}async function Oa(c){await wa(c.url)}
function Pa(c,a){c.ub=a.message;-1===c.Ma&&(c.Ma=setTimeout(()=>{c.Ma=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.ub)},250))}function Qa(c,a){console.warn("[Construct] Fullscreen request failed: ",a);m(c,"fullscreenerror",{isFullscreen:K.ca(),innerWidth:c.C(),innerHeight:c.v()})}
function La(c,a){c.ua!==a&&((c.ua=a)?c.h.hb():c.h.Ja(),m(c,"visibilitychange",{hidden:a}),!a&&c.h.da()&&(c=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(c,50),setTimeout(c,100),setTimeout(c,250),setTimeout(c,500)))}
function Ta(c,a,b){"Backspace"===b.key&&N(b);"nwjs"===c.h.g&&"u"===b.key&&(b.ctrlKey||b.metaKey)&&b.preventDefault();if(!c.A){var d=ta.get(b.code)||b.code;p(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},M)}}
function O(c,a,b,d){c.A||b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents||p(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.J,pageX:b.pageX,pageY:b.pageY+c.J,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function P(c,a,b){if(!c.A){var d=0;"mouse"===b.pointerType&&(d=c.Ua);p(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.J,pageX:b.pageX,pageY:b.pageY+c.J,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},M);"mouse"===b.pointerType&&(c.Ua=
b.buttons)}}function Ua(c,a,b){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";c.J=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,c.J=a))}}
function Va(c,a,b,d){const e=c.C(),f=c.v();c.Y=-1;e!=a||f!=b?m(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:K.ca(),cssDisplayMode:c.h.Ca()}):10>d&&Wa(c,e,f,d+1)}function Wa(c,a,b,d){-1!==c.Y&&clearTimeout(c.Y);c.Y=setTimeout(()=>Va(c,a,b,d),48)}
function Fa(c){c=c.Ya;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Xa(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
K.m(class extends self.G{constructor(c){super(c,"runtime");this.tb=!1;this.Y=-1;this.Ya="any";this.ua=this.ob=this.pb=!1;this.va=document.createElement("div");this.va.className="c3-screen-reader-text";this.va.setAttribute("aria-live","polite");document.body.appendChild(this.va);this.N=null;this.A=!1;this.ub="";this.Ma=-1;this.sb=!1;this.Ra=c.C();this.ja=c.v();this.J=this.ma=0;c.i("runtime","invoke-download",b=>{const d=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=
b;e.href=d;e.download=b;f.appendChild(e);e.click();f.removeChild(e)});c.i("runtime","load-webfonts",b=>Ga(b));c.i("runtime","raster-svg-image",b=>Ha(b));c.i("runtime","get-svg-image-size",b=>Ia(b));c.i("runtime","set-target-orientation",b=>{this.Ya=b.targetOrientation});c.i("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.i("runtime","post-to-debugger",b=>Ja(b));c.i("runtime","go-to-script",b=>Ja(b));c.i("runtime","before-start-ticking",()=>Ka(this));c.i("runtime","debug-highlight",
b=>{if(b.show){this.N||(this.N=document.createElement("div"),this.N.id="inspectOutline",document.body.appendChild(this.N));var d=this.N;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.N&&(this.N.style.display="none")});c.i("runtime","enable-device-orientation",()=>Ma(this));c.i("runtime","enable-device-motion",()=>Na(this));c.i("runtime","add-stylesheet",b=>Oa(b));c.i("runtime","script-create-worker",
b=>{const d=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});c.i("runtime","alert",b=>this.Ga(b));c.i("runtime","screen-reader-text",b=>{var d=b.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+b.id,d.textContent=b.text,this.va.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+b.id))?d.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===d?(d=document.getElementById("c3-sr-"+b.id))?
d.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});c.i("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.i("runtime","set-exporting-to-video",b=>{this.A=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=b.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");this.h.cb().style.display=
"";this.h.Ib()});c.i("runtime","export-to-video-progress",b=>Pa(this,b));c.i("runtime","exported-to-video",b=>{window.mc({type:"exported-video",arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})});c.i("runtime","exported-to-image-sequence",b=>{window.mc({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",b=>{const d=b.target;a.has(d.tagName.toLowerCase())||za(d)||b.preventDefault()});
window.addEventListener("selectstart",N);window.addEventListener("gesturehold",N);window.addEventListener("touchstart",N,{passive:!1});window.addEventListener("pointerdown",N,{passive:!1});this.Ua=0;window.addEventListener("mousedown",b=>{1===b.button&&b.preventDefault()});window.addEventListener("mousewheel",Da,{passive:!1});window.addEventListener("wheel",Da,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.A&&this.tb){var b=this.C();var d=this.v();if(this.h.eb()){if(this.sb){if(this.Ra===
b&&d<this.ja){this.ma=this.ja-d;Ua(this,this.ja,this.ma);b=void 0;break a}0<this.ma&&(this.ma=0,Ua(this,d,this.ma))}this.Ra=b;this.ja=d}m(this,"window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:K.ca(),cssDisplayMode:this.h.Ca()});this.h.da()&&(-1!==this.Y&&clearTimeout(this.Y),Va(this,b,d,0))}b=void 0}return b});window.addEventListener("fullscreenchange",()=>J(this));window.addEventListener("webkitfullscreenchange",()=>J(this));window.addEventListener("mozfullscreenchange",
()=>J(this));window.addEventListener("fullscreenerror",b=>Qa(this,b));window.addEventListener("webkitfullscreenerror",b=>Qa(this,b));window.addEventListener("mozfullscreenerror",b=>Qa(this,b));if(c.da()){let b=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>b&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);b=d});document.documentElement.setAttribute("ioswebview","")}this.Ta=new Set;this.kc=new WeakSet;this.ic=!1}ya(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,va)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}m(this,"window-blur",{parentHasFocus:a},va);this.Ua=0});window.addEventListener("focusin",a=>{a=a.target;(Aa.has(a.tagName.toLowerCase())||za(a))&&m(this,"keyboard-blur",null,va)});window.addEventListener("keydown",a=>Ta(this,"keydown",a));window.addEventListener("keyup",a=>Ta(this,"keyup",a));window.addEventListener("mousedown",a=>O(this,"mousedown",a,
ua));window.addEventListener("mousemove",a=>O(this,"mousemove",a,ua));window.addEventListener("mouseup",a=>O(this,"mouseup",a,ua));window.addEventListener("dblclick",a=>O(this,"dblclick",a,M));window.addEventListener("wheel",a=>{this.A||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.J,pageX:a.pageX,pageY:a.pageY+this.J,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},M)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
Xa(a.target)&&document.activeElement&&!Xa(document.activeElement)&&document.activeElement.blur();P(this,"pointerdown",a)});this.h.s&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{P(this,"pointermove",a)}):window.addEventListener("pointermove",a=>P(this,"pointermove",a));window.addEventListener("pointerup",a=>P(this,"pointerup",a));window.addEventListener("pointercancel",a=>P(this,"pointercancel",a));const c=()=>this.Ia();window.addEventListener("pointerup",
c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0);this.h.Db()&&!this.h.eb()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Ua(this,this.v(),navigator.virtualKeyboard.boundingRect.height)}));this.h.da()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}C(){return this.h.C()}v(){return this.h.v()}Ia(){var c=
[...this.Ta];this.Ta.clear();if(!this.ic)for(const a of c)(c=a.play())&&c.catch(()=>{this.kc.has(a)||this.Ta.add(a)})}Ga(c){alert(c.message)}});"use strict";async function oa(c){if(c.hc)throw Error("already initialised");c.hc=!0;var a=c.I.Fa(("playable-ad"===c.I.g?c.I.X:"")+"dispatchworker.js");c.La=await c.I.Aa(a,c.ea,{name:"DispatchWorker"});a=new MessageChannel;c.Oa=a.port1;c.La.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Va=await sa(c)}function pa(c){return[c.Oa,c.Va]}
async function sa(c){const a=c.xb.length;var b=c.I.Fa(("playable-ad"===c.I.g?c.I.X:"")+"jobworker.js");b=await c.I.Aa(b,c.ea,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.La.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.xb.push(b);return e.port1}
self.Gb=class{constructor(c){this.I=c;this.ea=c.o;this.ea="preview"===c.g?this.ea+"workers/":this.ea+c.X;this.jc=Math.min(navigator.hardwareConcurrency||2,16);this.La=null;this.xb=[];this.Va=this.Oa=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.j({vc:!0,wc:"workermain.js",$:["scripts/c3runtime.js"],wa:[],ab:"",sc:"scripts/",xa:[],Ab:"html5"}));"use strict";function Q(c){c.stopPropagation()}
self.j.m(class extends self.L{constructor(c){super(c,"button")}R(c,a){const b=document.createElement("input");var d=b;a.isCheckbox?(b.type="checkbox",d=document.createElement("label"),d.appendChild(b),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):b.type="button";d.style.position="absolute";d.addEventListener("pointerdown",Q);d.addEventListener("pointermove",
Q);d.addEventListener("pointerrawupdate",Q);d.addEventListener("pointerup",Q);d.addEventListener("mousedown",Q);d.addEventListener("mouseup",Q);d.addEventListener("keydown",Q);d.addEventListener("keyup",Q);d.addEventListener("contextmenu",e=>e.preventDefault());b.addEventListener("click",()=>y(this,"click",c,{isChecked:b.checked}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.u(d,a);return d}Ea(c){return"input"===c.tagName.toLowerCase()?c:c.firstChild}u(c,a){const b="input"===c.tagName.toLowerCase()?
c:c.firstChild;b.checked=a.isChecked;b.disabled=!a.isEnabled;c.title=a.title;c===b?b.value=a.text:c.lastChild.textContent=a.text}});"use strict";async function Ya(c,a,b){const d=await c.createWritable({keepExistingData:!!b});b&&(c=await c.getFile(),await d.seek(c.size));await d.write(a);await d.close()}function Za(c){c=c.replaceAll("\\","/");c.startsWith("/")&&(c=c.substring(1));c.endsWith("/")&&(c=c.substring(0,c.length-1));return c}
async function R(c,a){"prompt"===await c.queryPermission({mode:a})&&await c.requestPermission({mode:a})}const $a="<app> <web-resource> <current-app-data> <local-app-data> <roaming-app-data> <desktop> <documents> <downloads> <pictures> <profile> <saved-games> <screenshots> <videos>".split(" ");
async function ab(c,a){const b=a.pickerTag;a=a.pickerOpts;try{const d=await window.showSaveFilePicker(a);c.H.set(b,[d]);bb(c);return{isOk:!0,pickedFileNames:[d.name]}}catch(d){return console.warn("[Construct] Error showing save file picker: ",d),{isOk:!1}}}
async function cb(c,a){const b=a.pickerTag;a=a.pickerOpts;try{const d=await window.showOpenFilePicker(a);c.H.set(b,d);bb(c);return{isOk:!0,pickedFileNames:d.map(e=>e.name)}}catch(d){return console.warn("[Construct] Error showing open file picker: ",d),{isOk:!1}}}
async function db(c,a){const b=a.pickerTag;a=a.pickerOpts;try{const d=await window.showDirectoryPicker(a);c.H.set(b,[d]);bb(c);return{isOk:!0,pickedFolderNames:[d.name]}}catch(d){return console.warn("[Construct] Error showing folder picker: ",d),{isOk:!1}}}async function eb(c,a){const b=a.pickerTag,d=a.folderPath,e=a.text;a=a.keepExisting;try{const f=await S(c,b,d,!0);await Ya(f,e,a);return{isOk:!0}}catch(f){return console.error("[Construct] Error writing text file: ",f),{isOk:!1}}}
async function fb(c,a){const b=a.pickerTag,d=a.folderPath;a=a.arrayBuffer;try{const e=await S(c,b,d,!0);await Ya(e,a);return{isOk:!0}}catch(e){return console.error("[Construct] Error writing binary file: ",e),{isOk:!1}}}async function gb(c,a){const b=a.pickerTag;a=a.folderPath;try{return{isOk:!0,text:await (await (await S(c,b,a,!1)).getFile()).text()}}catch(d){return console.error("[Construct] Error reading text file: ",d),{isOk:!1}}}
async function hb(c,a){const b=a.pickerTag;a=a.folderPath;try{return{isOk:!0,arrayBuffer:await (await (await S(c,b,a,!1)).getFile()).arrayBuffer()}}catch(d){return console.error("[Construct] Error reading binary file: ",d),{isOk:!1}}}
async function ib(c,a){const b=a.pickerTag;a=a.folderPath;try{const {aa:d,K:e}=await T(c,b,a,!0);if(!e)throw Error("empty folder path");await d.getDirectoryHandle(e,{create:!0});return{isOk:!0}}catch(d){return console.error("[Construct] Error creating folder: ",d),{isOk:!1}}}
async function jb(c,a){const b=a.pickerTag,d=a.srcFolderPath;a=a.destFolderPath;try{const e=await T(c,b,a,!0),f=await T(c,b,d,!1);if(!f.K||!e.K)throw Error("empty folder path");const h=await f.aa.getFileHandle(f.K,{create:!1}),g=await e.aa.getFileHandle(e.K,{create:!0}),k=await h.getFile(),l=await g.createWritable();await k.stream().pipeTo(l);return{isOk:!0}}catch(e){return console.error("[Construct] Error copying file: ",e),{isOk:!1}}}
async function kb(c,a){const b=a.pickerTag,d=a.folderPath;a=a.isRecursive;try{const {aa:e,K:f}=await T(c,b,d,!1);if(!f)throw Error("empty folder path");await e.removeEntry(f,{recursive:a});return{isOk:!0}}catch(e){return console.error("[Construct] Error deleting: ",e),{isOk:!1}}}
async function lb(c,a){var b=a.pickerTag;a=a.folderPath;try{let {aa:d,K:e}=await T(c,b,a,!1);e&&(d=await d.getDirectoryHandle(e,{create:!1}));c=[];b=[];for await(const f of d.values())"file"===f.kind?b.push(f.name):"directory"===f.kind?c.push(f.name):console.warn(`unknown folder entry kind '${f.kind}' (name '${f.name}')`);return{isOk:!0,folderNames:c,fileNames:b}}catch(d){return console.error("[Construct] Error listing content: ",d),{isOk:!1}}}
function bb(c){m(c,"save-picker-map",{pickerMap:c.H})}async function mb(c,a,b){a=a.split("/");const d=a.pop();for(const e of a)c=await c.getDirectoryHandle(e,{create:b});return{aa:c,K:d}}
async function S(c,a,b,d){c=c.H.get(a);if(!Array.isArray(c)||0===c.length)throw Error(`nothing picked for tag '${a}'`);if(1===c.length&&"directory"===c[0].kind){a=c[0];await R(a,d?"readwrite":"read");b=Za(b);if(!b)throw Error("empty folder path");b=await mb(a,b,d);return await b.aa.getFileHandle(b.K,{create:d})}if(1!==c.length||b){for(const e of c)if(e.name===b)return await R(e,d?"readwrite":"read"),e;throw Error(`no file with name '${b}'`);}b=c[0];await R(b,d?"readwrite":"read");return b}
async function T(c,a,b,d){c=c.H.get(a);if(!Array.isArray(c)||0===c.length)throw Error(`nothing picked for tag '${a}'`);if(1===c.length&&"directory"===c[0].kind)return a=c[0],await R(a,d?"readwrite":"read"),b=Za(b),await mb(a,b,d);throw Error(`picker tag '${a}' is not for a folder`);}
self.j.m(class extends self.G{constructor(c){super(c,"filesystem");this.H=new Map;u(this,[["init",a=>this.S(a)],["show-save-file-picker",a=>ab(this,a)],["show-open-file-picker",a=>cb(this,a)],["show-folder-picker",a=>db(this,a)],["write-text-file",a=>eb(this,a)],["write-binary-file",a=>fb(this,a)],["read-text-file",a=>gb(this,a)],["read-binary-file",a=>hb(this,a)],["create-folder",a=>ib(this,a)],["copy-file",a=>jb(this,a)],["delete",a=>kb(this,a)],["list-content",a=>lb(this,a)]])}S(c){if(c=c.pickerMap)this.H=
c;c=this.h.rb;const a=new Set;for(let b=0,d=Math.min(c.length,$a.length);b<d;++b){const e=c[b],f=$a[b];e&&(this.H.set(f,[e]),a.add(f))}return{isSupported:!!window.showSaveFilePicker,additionalPickerTags:a,builtInPickerTags:$a}}});"use strict";function U(c){c.stopPropagation()}
self.j.m(class extends self.L{constructor(c){super(c,"file-chooser");w(this,"click",a=>{a.click()});w(this,"clear",a=>{a.value=""})}R(c,a){const b=document.createElement("input");b.type="file";b.style.position="absolute";b.style.userSelect="none";b.style.webkitUserSelect="none";b.addEventListener("pointerdown",U);b.addEventListener("pointermove",U);b.addEventListener("pointerrawupdate",U);b.addEventListener("pointerup",U);b.addEventListener("mousedown",U);b.addEventListener("mouseup",U);b.addEventListener("contextmenu",
d=>d.preventDefault());b.addEventListener("change",()=>v(this,"change",c,{files:Array.from(b.files)}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.u(b,a);return b}u(c,a){c.setAttribute("accept",a.accept);a.isMultiSelect?c.setAttribute("multiple",""):c.removeAttribute("multiple")}});"use strict";
self.j.m(class extends self.G{constructor(c){super(c,"mouse");u(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.h.cb().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function V(c){c.stopPropagation()}
self.j.m(class extends self.L{constructor(c){super(c,"sliderbar")}R(c,a){const b=document.createElement("input");b.type="range";b.style.position="absolute";b.style.userSelect="none";b.style.webkitUserSelect="none";b.addEventListener("pointerdown",V);b.addEventListener("pointermove",V);b.addEventListener("pointerrawupdate",V);b.addEventListener("pointerup",V);b.addEventListener("mousedown",V);b.addEventListener("mouseup",V);b.addEventListener("keydown",V);b.addEventListener("keyup",V);b.addEventListener("contextmenu",
d=>d.preventDefault());b.addEventListener("click",()=>y(this,"click",c));b.addEventListener("change",()=>v(this,"change",c,{value:parseFloat(b.value)}));b.addEventListener("input",()=>v(this,"input",c,{value:parseFloat(b.value)}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.u(b,a);return b}u(c,a){c.max=a.max;c.min=a.min;c.step=a.step;c.value=a.value;c.disabled=!a.isEnabled;c.title=a.title}});"use strict";function W(c){c.stopPropagation()}
function nb(c){13!==c.which&&27!==c.which&&c.stopPropagation()}
self.j.m(class extends self.L{constructor(c){super(c,"text-input");w(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}R(c,a){let b;const d=a.type;"textarea"===d?(b=document.createElement("textarea"),b.style.resize="none"):(b=document.createElement("input"),b.type=d);b.style.position="absolute";b.autocomplete="off";b.addEventListener("pointerdown",W);b.addEventListener("pointermove",W);b.addEventListener("pointerrawupdate",W);b.addEventListener("pointerup",W);b.addEventListener("mousedown",
W);b.addEventListener("mouseup",W);b.addEventListener("keydown",nb);b.addEventListener("keyup",nb);b.addEventListener("click",e=>{e.stopPropagation();y(this,"click",c)});b.addEventListener("dblclick",e=>{e.stopPropagation();y(this,"dblclick",c)});b.addEventListener("input",()=>v(this,"change",c,{text:b.value}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.u(b,a);return b}u(c,a){c.value=a.text;c.placeholder=a.placeholder;c.title=a.title;c.disabled=!a.isEnabled;c.readOnly=a.isReadOnly;
c.spellcheck=a.spellCheck;a=a.maxLength;0>a?c.removeAttribute("maxlength"):c.setAttribute("maxlength",a)}});"use strict";async function ob(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(c){return console.error("[Construct] Error requesting persistent storage: ",c),{isOk:!1}}}
self.j.m(class extends self.G{constructor(c){super(c,"localstorage");u(this,[["init",()=>this.S()],["request-persistent",()=>ob()]])}async S(){let c=!1;try{c=await navigator.storage.persisted()}catch(a){c=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:c}}});"use strict";let X=null,pb=null;window.addEventListener("beforeinstallprompt",c=>{c.preventDefault();X=c;pb&&m(pb,"install-available");return!1});function qb(){}
function rb(c){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(c,"sw-message",a.data))}
function sb(c){c=c.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}async function tb(){if(!X)return{result:"unavailable"};try{return X.prompt(),{result:(await X.userChoice).outcome}}catch(c){return console.error("[Construct] Requesting install failed: ",c),{result:"failed"}}}
self.j.m(class extends self.G{constructor(c){super(c,"browser");this.g="";u(this,[["get-initial-state",a=>{this.g=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>rb(this)],
["alert",a=>this.Ga(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ha(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>sb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===
a||this.h.B()?window.open(b,"_blank"):this.Bc||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if(this.h.B()||"macos-wkwebview"===this.g)self.j.sa(!0),this.h.M({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");
a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(b):a.mozRequestFullScreen?d=a.mozRequestFullScreen(b):a.msRequestFullscreen?d=a.msRequestFullscreen(b):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(qb)}}],["exit-fullscreen",()=>{if(this.h.B()||"macos-wkwebview"===this.g)self.j.sa(!1),this.h.M({type:"set-fullscreen",fullscreen:!1});
else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(qb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const b=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var h=document.querySelector(e);
f=h?[h]:[]}else f=[document.documentElement];e=f;for(const g of e)b.startsWith("--")?g.style.setProperty(b,d):g.style[b]=d}catch(g){console.warn("[Browser] Failed to set style: ",g)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var b=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),b={isOk:!1}}}return b}],["set-window-size",a=>{window.resizeTo(a.windowWidth,a.windowHeight)}],
["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}],["request-install",()=>tb()],["set-warn-on-close",a=>{a.enabled?window.addEventListener("beforeunload",this.qb):window.removeEventListener("beforeunload",this.qb)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});this.qb=a=>a.preventDefault();
document.addEventListener("backbutton",()=>{m(this,"backbutton")})}ya(){X?m(this,"install-available"):pb=this;window.addEventListener("appinstalled",()=>{m(this,"app-installed")})}Ga(c){alert(c.message)}Ha(c){c=c.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;c?a.focus():a.blur()}else c?window.focus():window.blur()}});"use strict";function ub(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=()=>a(d.result);d.onerror=()=>b(d.error);d.readAsArrayBuffer(c)})}
async function vb(c,a){a=a.text;let b=!1;try{await navigator.clipboard.writeText(a),b=!0}catch(d){console.error("Failed to copy to clipboard: ",d),b=!1}m(c,"copy-result",{isOk:b})}async function wb(c,a){const b=a.arrayBuffer;a=a.type;let d=!1;try{const e={};e[a]=new Blob([b],{type:a});await navigator.clipboard.write([new ClipboardItem(e)]);d=!0}catch(e){console.error("Failed to copy to clipboard: ",e),d=!1}m(c,"copy-result",{isOk:d})}
async function xb(c){let a=!1,b="";try{b=await navigator.clipboard.readText(),a=!0}catch(d){console.error("Failed to paste: ",d),b="",a=!1}m(c,"request-paste-text-result",{isOk:a,text:b})}
async function yb(c){let a=!1,b=[];try{var d=await navigator.clipboard.read();if(1<=d.length){const e=d[0];d=[];const f=e.types;for(const h of f)d.push((async()=>{const g=await e.getType(h);return await ub(g)})());b=(await Promise.all(d)).map((h,g)=>[f[g],h]);a=!0}else a=!1}catch(e){console.error("Failed to paste: ",e),a=!1}m(c,"request-paste-binary-result",{isOk:a,binary:b})}
async function zb(c,a){if((new Set(["canvas","body","html"])).has((a.target.tagName||"").toLowerCase())){a.preventDefault();var b=a.clipboardData.getData("text");b?m(c,"window-paste-text",{text:b}):1<=a.clipboardData.files.length&&(a=a.clipboardData.files[0],b=await ub(a),m(c,"window-paste-binary",{arrayBuffer:b,type:a.type}))}}
self.j.m(class extends self.G{constructor(c){super(c,"clipboard");u(this,[["copy-text",a=>vb(this,a)],["copy-binary",a=>wb(this,a)],["request-paste-text",()=>xb(this)],["request-paste-binary",()=>yb(this)]]);window.addEventListener("paste",a=>zb(this,a))}});"use strict";async function Ab(c,a){a=a.type;let b=!0;0===a?b=await Bb():1===a&&(b=await Cb());m(c,"permission-result",{type:a,result:b})}
async function Bb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request orientation permission: ",c),!1}}
async function Cb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request motion permission: ",c),!1}}self.j.m(class extends self.G{constructor(c){super(c,"touch");t(this,"request-permission",a=>Ab(this,a))}});"use strict";function Z(c){c.stopPropagation()}function Db(c){const a=document.createElement("option");a.text=c;return a}
function Eb(c){const a=c.selectedIndex,b=[];for(let d=0,e=c.length;d<e;++d)c.options[d].selected&&b.push(d);return{selectedIndex:a,selectedIndices:b}}
self.j.m(class extends self.L{constructor(c){super(c,"list");w(this,"set-selected-index",(a,b)=>{a.selectedIndex=b.selectedIndex});w(this,"add-item",(a,b)=>{const d=b.index;b=Db(b.text);0>d?a.add(b):a.add(b,d)});w(this,"remove-item",(a,b)=>{a.remove(b.index)});w(this,"set-item",(a,b)=>{a.options[b.index].text=b.text});w(this,"clear",a=>{a.innerHTML=""});w(this,"load-state",(a,b)=>{a.innerHTML="";for(const d of b.items)a.add(Db(d));a.selectedIndex=b.selectedIndex;for(const d of b.selectedIndices)if(b=
a.options[d])b.selected=!0})}R(c,a){const b=a.isDropdown,d=a.isMultiSelect,e=a.items,f=document.createElement("select");f.style.position="absolute";f.style.userSelect="none";f.style.webkitUserSelect="none";f.multiple=d;b||(f.size=2);for(const h of e)f.add(Db(h));f.addEventListener("pointerdown",Z);f.addEventListener("pointermove",Z);f.addEventListener("pointerrawupdate",Z);f.addEventListener("pointerup",Z);f.addEventListener("mousedown",Z);f.addEventListener("mouseup",Z);f.addEventListener("click",
h=>{h.stopPropagation();y(this,"click",c,Eb(f))});f.addEventListener("dblclick",h=>{h.stopPropagation();y(this,"dblclick",c,Eb(f))});f.addEventListener("change",()=>v(this,"change",c,Eb(f)));a.id&&(f.id=a.id);a.className&&(f.className=a.className);this.u(f,a);return f}u(c,a){c.title=a.title;c.disabled=!a.isEnabled;c.multiple=!!a.isMultiSelect}});
